from .LaplacianEigenmaps import LaplacianEigenmaps
from .GraphFactorization import GraphFactorization
from .GraRep import GraRep
from .HOPE import HOPE
from .DeepWalk import DeepWalk
from .Node2Vec import Node2Vec
from .LINE import LINE
from .HARP import HARP
from .Struc2Vec import Struc2Vec
from .GraphWave import GraphWave